name: Symfony CI

on:
  push:
    branches:
      - test
      - prod
      - preprod
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: |
          cd ugselweb2  # Aller dans le répertoire où se trouve composer.json
          composer install --no-interaction

      - name: Run PHP CS Linter
        run: |
          cd ugselweb2  # Exécuter dans le bon répertoire
          vendor/bin/php-cs-fixer fix --dry-run --diff

  tests:
    runs-on: ubuntu-latest
    needs: lint
    if: github.ref == 'refs/heads/test' || github.ref == 'refs/heads/prod'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: |
          cd ugselweb2  # Toujours aller dans le bon répertoire
          composer install --no-interaction

      - name: Run tests
        run: |
          cd ugselweb2  # Exécuter les tests dans ce répertoire
          ./vendor/bin/phpunit --configuration phpunit.xml.dist

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Push to preprod
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.email "clement.marie24@gmail.com"
          git config --global user.name "Clementbot"
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/MARIE-Clement-2225058b/Maintenance-de-code.git
          git fetch origin
          if ! git show-ref --verify --quiet refs/heads/preprod; then
            git checkout -b preprod
            git push origin preprod
          else
            git checkout preprod
            git pull origin preprod --rebase  # Récupère les dernières modifications avec rebase
            git merge main
            git push origin preprod
          fi
