name: Symfony CI

on:
  push:
    branches:
      - test
      - prod
      - preprod
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: |
          cd ugselweb2  # Aller dans le répertoire où se trouve composer.json
          composer install --no-interaction

      - name: Run PHP CS Fixer
        run: |
          cd ugselweb2  # Exécuter dans le bon répertoire
          vendor/bin/php-cs-fixer fix --diff .  # Automatically fix the issues

  tests:
    runs-on: ubuntu-latest
    needs: lint
    if: github.ref == 'refs/heads/test' || github.ref == 'refs/heads/prod'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: |
          cd ugselweb2  # Toujours aller dans le bon répertoire
          composer install --no-interaction

      - name: Run tests
        run: |
          cd ugselweb2  # Exécuter les tests dans ce répertoire
